services:
  - type: web
    name: sortyx-waste-classifier
    runtime: python
    plan: starter  # Use 'free' for testing, 'starter' for production
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: GEMINI_API_KEY
        sync: false  # Set this manually in Render dashboard
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
